### ISSUE TITLE
semant rejecting OK constructor

### ISSUE THREAD

**Issue by joshuazweig** [joshuazweig/C-#12]
In jz-codegen, if you run `construct_test.cm` after `make all` semant throws an error saying that (curve, stone, stone) is not a legal way to construct a point. However, I believe this is exactly the case (at least it is in the LRM).

**Comment by mikecmtong** [comment]
Just change Line 150

(Curve, Mint, Mint) -> ...

to

(Curve, Stone, Stone) -> ...

**Comment by joshuazweig** [comment]
Resolved by #14
