### ISSUE TITLE
Creating stone from string

### ISSUE THREAD

**Issue by joshuazweig** [joshuazweig/C-#19]
To create a stone from a string literal, we call stone_create_func. This function uses OpenSSLs bin2bn function. This means that 

stone x = "hello" 

will create a stone where the bignum value is the hexvalue of the ASCII string "hello."

**Comment by mikecmtong** [comment]
Fixed this -- it now declares with positive/negative values, e.g.

stone x;
x = "123";

makes x have value 123.

**Comment by joshuazweig** [comment]
Sweeeet thanks a lot man. Should we close the issue?

**Comment by joshuazweig** [comment]
Fixed in #30
