### ISSUE TITLE
When a mint is declared, it doesn't reduce the value

### ISSUE THREAD

**Issue by mikecmtong** [joshuazweig/C-#21]
e.g. declaring something as <23, 5> should make the inherent value be <3, 5>. Important if the user wants to access the value before doing any arithmetic on it. (This is probably a small change and easy to do)

**Comment by mikecmtong** [comment]
Fixed this part, but now if a mint is declared with a negative bignum as a value, the value will just be negative forever.

**Comment by joshuazweig** [comment]
Thanks @mikecmtong ! 
How should we handle that do you think? Just say no negative bignums? I believe that is the current rule
